# Generated by Django 4.2 on 2023-11-13 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupdiscussion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('Description', tinymce.models.HTMLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='HouseComment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('sheduleDate', models.DateField(null=True)),
                ('comment', models.CharField(max_length=100)),
                ('houses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupdiscussion.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.basemodel',),
        ),
    ]
