# Generated by Django 4.2 on 2023-11-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupdiscussion', '0002_house_housecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housecomment',
            old_name='houses',
            new_name='houses_id',
        ),
    ]
