# Generated by Django 4.2 on 2023-11-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupdiscussion', '0003_rename_houses_housecomment_houses_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housecomment',
            old_name='houses_id',
            new_name='houses',
        ),
    ]
